### ISSUE TITLE
nest-cli unable to copy assets to dist

### ISSUE THREAD

**Issue by dozie** [nestjs/nest-cli#1004]
## Unable to copy assets for build

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

According to the documentation https://docs.nestjs.com/cli/monorepo#assets one can copy assets when including by including the assets in the compilerOptions contained in the nest-cli.json.

I have the following configuration in my `nest-cli.json`
```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "assets": [
      "config/**/*.yaml",
      "config/**/*.yml"
    ],
    "watchAssets": true
  }
}
```
## Current behavior

- yml configuration contained in a `config` directory are not copied.

## Expected behavior
- yml configuration files to be successfully copied.

## Environment

```

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Catalina
NodeJS Version : v14.14.0
NPM Version    : 6.14.10 

[Nest CLI]
Nest CLI Version : 7.5.4 

[Nest Platform Information]
platform-express version : 7.5.1
common version           : 7.5.1
config version           : 0.6.1
core version             : 7.5.1

```

In my application I am using an express adapter and I have my config file in a config folder, `config/config.yaml`.
Below is a sample of my index file & config file

```
const expressApp = express();
const createFunction = async (expressInstance): Promise<void> => {
    const app = await NestFactory.create(
        AppModule,
        new ExpressAdapter(expressInstance),
    );
    app.useGlobalFilters(new AllExceptionFilter());
    await app.init();
};



createFunction(expressApp)
    .then(() => console.log('nest application ready'))
    .catch(error => console.error('nest app error', error));


export const api = functions.https.onRequest(expressApp);
```

```
slack:
  api:
    authorize: 'https://slack.com/api/oauth.v2.access'
    userinfo: 'https://slack.com/api/users.info'
  secret:
    client: 'enter your client secret'
    signing: 'enter your signing secret'
  client_id: 'random id '
  app_id: 'random app id'
  app:
    oauth_access_token: 'enter oauth token'
  bot:
    oauth_access_token: 'enter oauth token'

firebase:
  db:
    url: 'https://path/to/database'

```
