### ISSUE TITLE
Dev mode restart loop 

### ISSUE THREAD

**Issue by pizzurro** [nestjs/nest-cli#1996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Installed Nest cli version 9.3.0 and created a project `nest new <project name>` with npm package manager option

Started project with `npm run start:dev`

Project continuously restarts despite no files changing.  Seems to have something to do with Typescript 4.9.5 (installed due to semver ^4.7.4) .  Reverting Typescript to version 4.7.4 corrects issue.  

### Minimum reproduction code

Default code

### Steps to reproduce

1. `nest new <project name>`
2. `npm run start:dev`

### Expected behavior

Application runs in watch mode without repetitive restart

### Package version

9.3.0

### NestJS version

9.0.0

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by pizzurro** [comment]
This fixes it.  Should probably be in the tsconfig already to prevent this, no?

**Comment by micalevisk** [comment]
@pizzurro maybe? but I'm not sure as this is a windows-only issue... 

This isn't related with nestjs's CLI, AFIAK

**Comment by micalevisk** [comment]
than that must be a bug on `@nestjs/cli`

in this case, we should fix it instead of having that as workaround.  
Would you like to create a PR for this?

**Comment by kamilmysliwiec** [comment]
I can't reproduce this issue

**Comment by tafaust** [comment]
@kamilmysliwiec what IDE are you using and are you so kind to share your launch configuration?

I experience the same issue with vscode by typing
```zsh
yarn run start:debug
```
in my zsh integrated terminal with 
```
    "start": "nest start",
    "start:dev": "NODE_ENV=development nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
```
in my package.json.
This is my `.yarnrc.yml`:
```yaml
enableTelemetry: false

nodeLinker: pnp

checksumBehavior: update

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  myOrgOnGh:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'
```

Using "@nestjs/cli" at version "^10.1.18".
